// <auto-generated />
using System;
using LocaVisite.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocaVisite.Api.Migrations
{
    [DbContext(typeof(LocaVisiteContext))]
    [Migration("20260901043025_MigrationInitiale")]
    partial class MigrationInitiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocaVisite.Api.Models.Communication", b =>
                {
                    b.Property<int>("IdCommunication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_communication");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommunication"));

                    b.Property<string>("Contenu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_envoi");

                    b.Property<int>("IdVisite")
                        .HasColumnType("int")
                        .HasColumnName("id_visite");

                    b.Property<string>("StatutEnvoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("statut_envoi");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.HasKey("IdCommunication");

                    b.HasIndex("IdVisite");

                    b.ToTable("COMMUNICATION");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Disponibilite", b =>
                {
                    b.Property<int>("IdDisponibilite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_disponibilite");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDisponibilite"));

                    b.Property<TimeOnly>("HeureDebut")
                        .HasColumnType("time")
                        .HasColumnName("heure_debut");

                    b.Property<TimeOnly>("HeureFin")
                        .HasColumnType("time")
                        .HasColumnName("heure_fin");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    b.Property<int>("JourSemaine")
                        .HasColumnType("int")
                        .HasColumnName("jour_semaine");

                    b.HasKey("IdDisponibilite");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("DISPONIBILITE");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Logement", b =>
                {
                    b.Property<int>("IdLogement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_logement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogement"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("adresse");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code_postal");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<decimal>("LoyerMensuel")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("loyer_mensuel");

                    b.Property<int>("NbPieces")
                        .HasColumnType("int")
                        .HasColumnName("nb_pieces");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("statut");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ville");

                    b.HasKey("IdLogement");

                    b.ToTable("LOGEMENT");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Photo", b =>
                {
                    b.Property<int>("IdPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_photo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhoto"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("chemin_fichier");

                    b.Property<int>("IdLogement")
                        .HasColumnType("int")
                        .HasColumnName("id_logement");

                    b.Property<int>("OrdreAffichage")
                        .HasColumnType("int")
                        .HasColumnName("ordre_affichage");

                    b.HasKey("IdPhoto");

                    b.HasIndex("IdLogement");

                    b.ToTable("PHOTO");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Prospect", b =>
                {
                    b.Property<int>("IdProspect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_prospect");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProspect"));

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("courriel");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<bool>("PossedeMobile")
                        .HasColumnType("bit")
                        .HasColumnName("possede_mobile");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdProspect");

                    b.ToTable("PROSPECT");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.RapportVisite", b =>
                {
                    b.Property<int>("IdRapport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rapport");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRapport"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commentaire");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_creation");

                    b.Property<int>("IdVisite")
                        .HasColumnType("int")
                        .HasColumnName("id_visite");

                    b.Property<string>("NiveauInteret")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("niveau_interet");

                    b.Property<bool>("ProspectPresent")
                        .HasColumnType("bit")
                        .HasColumnName("prospect_present");

                    b.HasKey("IdRapport");

                    b.HasIndex("IdVisite")
                        .IsUnique();

                    b.ToTable("RAPPORT_VISITE");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_utilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("courriel");

                    b.Property<string>("FournisseurAuth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fournisseur_auth");

                    b.Property<string>("IdExterne")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("id_externe");

                    b.Property<string>("MotDePasse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("mot_de_passe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prenom");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Courriel")
                        .IsUnique();

                    b.ToTable("UTILISATEUR");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Visite", b =>
                {
                    b.Property<int>("IdVisite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_visite");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVisite"));

                    b.Property<DateOnly?>("DatePrevue")
                        .HasColumnType("date")
                        .HasColumnName("date_prevue");

                    b.Property<DateOnly>("DateSouhaitee")
                        .HasColumnType("date")
                        .HasColumnName("date_souhaitee");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("distance_km");

                    b.Property<int>("DureePrevue")
                        .HasColumnType("int")
                        .HasColumnName("duree_prevue");

                    b.Property<int?>("DureeReelle")
                        .HasColumnType("int")
                        .HasColumnName("duree_reelle");

                    b.Property<TimeOnly?>("HeureArriveePrevue")
                        .HasColumnType("time")
                        .HasColumnName("heure_arrivee_prevue");

                    b.Property<TimeOnly?>("HeurePrevue")
                        .HasColumnType("time")
                        .HasColumnName("heure_prevue");

                    b.Property<DateTime?>("HeurePunchIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("heure_punch_in");

                    b.Property<DateTime?>("HeurePunchOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("heure_punch_out");

                    b.Property<TimeOnly>("HeureSouhaiteeDebut")
                        .HasColumnType("time")
                        .HasColumnName("heure_souhaitee_debut");

                    b.Property<TimeOnly>("HeureSouhaiteeFin")
                        .HasColumnType("time")
                        .HasColumnName("heure_souhaitee_fin");

                    b.Property<int?>("IdAgent")
                        .HasColumnType("int")
                        .HasColumnName("id_agent");

                    b.Property<int>("IdLogement")
                        .HasColumnType("int")
                        .HasColumnName("id_logement");

                    b.Property<int>("IdProspect")
                        .HasColumnType("int")
                        .HasColumnName("id_prospect");

                    b.Property<string>("LieuOrigine")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("lieu_origine");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("statut");

                    b.HasKey("IdVisite");

                    b.HasIndex("IdAgent");

                    b.HasIndex("IdLogement");

                    b.HasIndex("IdProspect");

                    b.ToTable("VISITE");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Communication", b =>
                {
                    b.HasOne("LocaVisite.Api.Models.Visite", "Visite")
                        .WithMany("Communications")
                        .HasForeignKey("IdVisite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visite");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Disponibilite", b =>
                {
                    b.HasOne("LocaVisite.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("Disponibilites")
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Photo", b =>
                {
                    b.HasOne("LocaVisite.Api.Models.Logement", "Logement")
                        .WithMany("Photos")
                        .HasForeignKey("IdLogement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logement");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.RapportVisite", b =>
                {
                    b.HasOne("LocaVisite.Api.Models.Visite", "Visite")
                        .WithOne("RapportVisite")
                        .HasForeignKey("LocaVisite.Api.Models.RapportVisite", "IdVisite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visite");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Visite", b =>
                {
                    b.HasOne("LocaVisite.Api.Models.Utilisateur", "Agent")
                        .WithMany("Visites")
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LocaVisite.Api.Models.Logement", "Logement")
                        .WithMany("Visites")
                        .HasForeignKey("IdLogement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LocaVisite.Api.Models.Prospect", "Prospect")
                        .WithMany("Visites")
                        .HasForeignKey("IdProspect")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Logement");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Logement", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Visites");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Prospect", b =>
                {
                    b.Navigation("Visites");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("Disponibilites");

                    b.Navigation("Visites");
                });

            modelBuilder.Entity("LocaVisite.Api.Models.Visite", b =>
                {
                    b.Navigation("Communications");

                    b.Navigation("RapportVisite");
                });
#pragma warning restore 612, 618
        }
    }
}
